development:
  primary:
    adapter: postgresql
    encoding: unicode
    database: defaultdb
    pool: 5
    username: avnadmin
    password: 'AVNS_AFR9Ey4S0DZUP1Zi0Gd'
    host: pg-2ca3c248-jemskedjar-1459.f.aivencloud.com
    port: 20853
    sslmode: require
    sslrootcert: config/ssl/ca.pem
  queue:
    adapter: postgresql
    encoding: unicode
    database: queue_db
    pool: 5
    username: avnadmin
    password: 'AVNS_AFR9Ey4S0DZUP1Zi0Gd'
    host: pg-2ca3c248-jemskedjar-1459.f.aivencloud.com
    port: 20853
    sslmode: require
    sslrootcert: config/ssl/ca.pem
  cache:
    adapter: postgresql
    encoding: unicode
    database: cache_db
    pool: 5
    username: avnadmin
    password: 'AVNS_AFR9Ey4S0DZUP1Zi0Gd'
    host: pg-2ca3c248-jemskedjar-1459.f.aivencloud.com
    port: 20853
    sslmode: require
    sslrootcert: config/ssl/ca.pem
  cable:
    adapter: postgresql
    encoding: unicode
    database: test_cable_db
    pool: 5
    username: avnadmin
    password: 'AVNS_AFR9Ey4S0DZUP1Zi0Gd'
    host: pg-2ca3c248-jemskedjar-1459.f.aivencloud.com
    port: 20853
    sslmode: require
    sslrootcert: config/ssl/ca.pem

test:
  primary:
    adapter: postgresql
    encoding: unicode
    database: test_defaultdb
    pool: 5
    username: avnadmin
    password: 'AVNS_AFR9Ey4S0DZUP1Zi0Gd'
    host: pg-2ca3c248-jemskedjar-1459.f.aivencloud.com
    port: 20853
    sslmode: require
    sslrootcert: config/ssl/ca.pem
  queue:
    adapter: postgresql
    encoding: unicode
    database: test_queue_db
    pool: 5
    username: avnadmin
    password: 'AVNS_AFR9Ey4S0DZUP1Zi0Gd'
    host: pg-2ca3c248-jemskedjar-1459.f.aivencloud.com
    port: 20853
    sslmode: require
    sslrootcert: config/ssl/ca.pem
  cache:
    adapter: postgresql
    encoding: unicode
    database: test_cache_db
    pool: 5
    username: avnadmin
    password: 'AVNS_AFR9Ey4S0DZUP1Zi0Gd'
    host: pg-2ca3c248-jemskedjar-1459.f.aivencloud.com
    port: 20853
    sslmode: require
    sslrootcert: config/ssl/ca.pem
  cable:
    adapter: postgresql
    encoding: unicode
    database: test_cable_db
    pool: 5
    username: avnadmin
    password: 'AVNS_AFR9Ey4S0DZUP1Zi0Gd'
    host: pg-2ca3c248-jemskedjar-1459.f.aivencloud.com
    port: 20853
    sslmode: require
    sslrootcert: config/ssl/ca.pem

production:
  primary:
    adapter: postgresql
    encoding: unicode
    database: defaultdb
    pool: 5
    username: avnadmin
    password: 'AVNS_AFR9Ey4S0DZUP1Zi0Gd'
    host: pg-2ca3c248-jemskedjar-1459.f.aivencloud.com
    port: 20853
    sslmode: require
    sslrootcert: config/ssl/ca.pem
  queue:
    adapter: postgresql
    encoding: unicode
    database: prod_queue_db
    pool: 5
    username: avnadmin
    password: 'AVNS_AFR9Ey4S0DZUP1Zi0Gd'
    host: pg-2ca3c248-jemskedjar-1459.f.aivencloud.com
    port: 20853
    sslmode: require
    sslrootcert: config/ssl/ca.pem
  cache:
    adapter: postgresql
    encoding: unicode
    database: prod_cache_db
    pool: 5
    username: avnadmin
    password: 'AVNS_AFR9Ey4S0DZUP1Zi0Gd'
    host: pg-2ca3c248-jemskedjar-1459.f.aivencloud.com
    port: 20853
    sslmode: require
    sslrootcert: config/ssl/ca.pem
  cable:
    adapter: postgresql
    encoding: unicode
    database: test_cable_db
    pool: 5
    username: avnadmin
    password: 'AVNS_AFR9Ey4S0DZUP1Zi0Gd'
    host: pg-2ca3c248-jemskedjar-1459.f.aivencloud.com
    port: 20853
    sslmode: require
    sslrootcert: config/ssl/ca.pem
