development:
  adapter: postgresql
  encoding: unicode
  database: defaultdb
  pool: 5
  username: avnadmin
  password: 'AVNS_AFR9Ey4S0DZUP1Zi0Gd'
  host: pg-2ca3c248-jemskedjar-1459.f.aivencloud.com
  port: 20853
  sslmode: require
  sslrootcert: 'path_to_ca_certificate.pem'  # Path to your CA certificate (optional if required)

test:
  adapter: postgresql
  encoding: unicode
  database: your_test_database_name
  pool: 5
  username: avnadmin
  password: 'AVNS_AFR9Ey4S0DZUP1Zi0Gd'
  host: pg-2ca3c248-jemskedjar-1459.f.aivencloud.com
  port: 20853
  sslmode: require
  sslrootcert: 'path_to_ca_certificate.pem'

production:
  adapter: postgresql
  encoding: unicode
  database: defaultdb
  pool: 5
  username: avnadmin
  password: 'AVNS_AFR9Ey4S0DZUP1Zi0Gd'
  host: pg-2ca3c248-jemskedjar-1459.f.aivencloud.com
  port: 20853
  sslmode: require
  sslrootcert: 'path_to_ca_certificate.pem'
