development:
  primary:
    adapter: postgresql
    encoding: unicode
    database: defaultdb
    pool: 5
    username: avnadmin
    password: 'AVNS_AFR9Ey4S0DZUP1Zi0Gd'
    host: pg-2ca3c248-jemskedjar-1459.f.aivencloud.com
    port: 20853
    sslmode: require
    sslrootcert: config/ssl/ca.pem
  queue:
    adapter: postgresql
    encoding: unicode
    database: queue_dev
    pool: 5
    username: avnadmin
    password: 'AVNS_AFR9Ey4S0DZUP1Zi0Gd'
    host: pg-2ca3c248-jemskedjar-1459.f.aivencloud.com
    port: 20853
    sslmode: require
    sslrootcert: config/ssl/ca.pem

test:
  primary:
    adapter: postgresql
    encoding: unicode
    database: your_test_database_name
    pool: 5
    username: avnadmin
    password: 'AVNS_AFR9Ey4S0DZUP1Zi0Gd'
    host: pg-2ca3c248-jemskedjar-1459.f.aivencloud.com
    port: 20853
    sslmode: require
    sslrootcert: config/ssl/ca.pem
  queue:
    adapter: postgresql
    encoding: unicode
    database: queue_test
    pool: 5
    username: avnadmin
    password: 'AVNS_AFR9Ey4S0DZUP1Zi0Gd'
    host: pg-2ca3c248-jemskedjar-1459.f.aivencloud.com
    port: 20853
    sslmode: require
    sslrootcert: config/ssl/ca.pem

production:
  primary:
    adapter: postgresql
    encoding: unicode
    database: defaultdb
    pool: 5
    username: avnadmin
    password: 'AVNS_AFR9Ey4S0DZUP1Zi0Gd'
    host: pg-2ca3c248-jemskedjar-1459.f.aivencloud.com
    port: 20853
    sslmode: require
    sslrootcert: config/ssl/ca.pem
  queue:
    adapter: postgresql
    encoding: unicode
    database: queue_prod
    pool: 5
    username: avnadmin
    password: 'AVNS_AFR9Ey4S0DZUP1Zi0Gd'
    host: pg-2ca3c248-jemskedjar-1459.f.aivencloud.com
    port: 20853
    sslmode: require
    sslrootcert: config/ssl/ca.pem

cable:
  adapter: postgresql
  encoding: unicode
  database: defaultdb
  pool: 5
  username: avnadmin
  password: 'AVNS_AFR9Ey4S0DZUP1Zi0Gd'
  host: pg-2ca3c248-jemskedjar-1459.f.aivencloud.com
  port: 20853
  sslmode: require
  sslrootcert: config/ssl/ca.pem
